import Head from "next/head";
import formImage from "../img/form.png";
import Image from "next/image";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion as m } from "framer-motion";
import { CredentialResponse, GoogleOAuthProvider } from "@react-oauth/google";
import { GoogleLogin } from '@react-oauth/google';
import { jwtDecode } from "jwt-decode";
import React, { useState } from 'react';


export default function Home() {
  const router = useRouter();
  const [loggedIn, setLoggedIn] = useState(false);
  const [isChecked, setIsChecked] = useState(false);
  const handleCheckboxChange = () => {
    setIsChecked(!isChecked);
  };

  const handleGoogleSignIn = (credentialResponse: { credential: string; }) => {
    const details = jwtDecode(credentialResponse.credential);
    console.log(details);
    console.log(credentialResponse);
    setLoggedIn(true);

  };

  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "Philippines",
      terms: "",
    },

    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 20 characters or less.")
        .required("Name is required"),
      email: Yup.string()
        .email("Invalid email address")
        .required("Email is required"),
      terms: Yup.array().required("Terms of service must be checked"),
    }),

    onSubmit: (values: any) => {
      console.log("form submitted");
      console.log(values);
      router.push({ pathname: "/home", query: values });
    },
  });

  function credentialResponse(credentialResponse: CredentialResponse): void {
    throw new Error("Function not implemented.");
  }

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full"
    >
      <Head>
        <title>HTF Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/htf.ico" />
      </Head>

      <main className="bg-slate-900 min-h-screen flex items-center justify-center">
        <form
          onSubmit={formik.handleSubmit}
          className="flex flex-col lg:flex-row w-10/12 lg:w-8/12 bg-white rounded-xl mx-auto shadow-lg overflow-hidden"
        >
          <div className="flex-1 text-slate-700 p-20">
            <h1 className="text-3xl pb-2 font-latoBold">
              Lets get started 👋
            </h1>
            <p className="text-lg  text-gray-500">
              Please fill up the form in Below or Agree to the terms and signup with google instead

            </p>


            <div className="mt-6 flex flex-col justify-center">
              {/* Name input field */}
              <div className="pb-4 ">
                <label
                  htmlFor="name"
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-400"
                      : ""
                  } `}
                > 
                </label>
                <p className="text-sm font-latoBold text-red-400 "></p>
                <input
                  className="w-auto border-2 border-gray-500 p-2 rounded-md  focus:border-teal-500 focus:ring-teal-500 text-white md:max-w-2xl md-w-1/5 "
                  type="text"
                  name="name"
                  placeholder="Enter your name"
                  onChange={formik.handleChange}
                  value={formik.values.name}
                  onBlur={formik.handleBlur}
                />
              </div>
              {/* Email input field */}
              <div className="pb-4">
                <label
                  htmlFor="email"
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.email && formik.errors.email
                      ? "text-red-400"
                      : ""
                  }`}
                >
          
                </label>

                <p></p>
                <input
                  className="w-auto border-2 border-gray-500 p-2 rounded-md  focus:border-teal-500 focus:ring-teal-500 text-white"
                  type="email"
                  name="email"
                  placeholder="Enter your email address"
                  onChange={formik.handleChange}
                  value={formik.values.email}
                  onBlur={formik.handleBlur}
                />
              </div>
              {/* Country input field */}
              <div className="pb-4">
                <label
                  htmlFor="country"
                  className="block font-latoBold text-sm pb-2"
                >
                  Country
                </label>
                <select
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500 text-white"
                  name="country"
                  onChange={formik.handleChange}
                  value={formik.values.country}
                >
                  <option>United States</option>
                  <option>United Kingdom</option>
                  <option>Germany</option>
                  <option>China</option>
                  <option>Japan</option>
                  <option>India</option>
                  <option>Malaysia</option>
                  <option>Jordan</option>
                  <option>Philippines</option>
                </select>
              </div>
              {/* Terms of service*/}
              <div className="pb-4">
                <label
                  htmlFor="terms"
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.terms && formik.errors.terms
                      ? "text-red-400"
                      : ""
                  }`}
                
                >
         
                </label>

                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    name="terms"
                    value="checked"
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
             
                 
                    className="h-5 w-5 text-teal-500 border-2  background-gray-500 focus:border-teal-500 focus:ring-teal-500"
                  />
                  <p className="text-sm font-latoBold text-gray-500">
                    I agree to the Terms and Service that my data will be taken
                    and sold.
                  </p>
                  
                </div>
        
  <div className="flex items-center gap-3">
      <input 
        type="checkbox" 
        name="terms"
        value="checked"
        checked={isChecked} 
        onChange={handleCheckboxChange}
        className="h-5 w-5 text-teal-500 border-2  background-gray-500 focus:border-teal-500 focus:ring-teal-500"
        />
        <p className="text-sm font-latoBold text-gray-500">
        Please check the box for log in your google
        </p> 
      </div>
                {isChecked && (
        <GoogleOAuthProvider clientId="354546675754-l0qb6u36crsh957js7lt54soesom752j.apps.googleusercontent.com">
          <GoogleLogin
            onSuccess={credentialResponse}
            onError={() => {
              console.log('Login Failed');
            }}
          />
        </GoogleOAuthProvider>
      )}
              </div>
              <button
                type="submit"
                className="bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full"
              >
                  Start
              </button>
              
            </div>
          </div>
          <div className="relative flex-1 hidden sm:block">
            <Image
              className=" object-cover rounded-lg"
              fill
              priority
              src={formImage}
              alt="form-learn"
              
            />
  
          </div>
        </form>
          
      </main>
    </m.div>
  );
}